version: "3.8"

services:
  sql-database:
    container_name: sql-database
    image: postgres:latest
    environment:
      - POSTGRES_DB=4Tables
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - mynet
  
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - sql-database
    expose:
    - 8080
    environment:
      ConnectionStrings__DefaultConnection: "Server=sql-database;Port=5432;Database=4Tables;Username=postgres;Password=admin"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge